import React from 'react';
import type { GetServerSidePropsContext, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { getSession, signIn } from 'next-auth/react';

import LandingPageCard from '~/components/LandingPageCard';
import vector1 from '~/images/vector2.png';
import vector2 from '~/images/vector3.png';
import vector3 from '~/images/vector1.png';
import image1 from '~/images/image 1.png';
import image2 from '~/images/image 2.png';
import company1 from '~/images/companies/company1.png';
import company2 from '~/images/companies/company2.png';
import company3 from '~/images/companies/company3.png';
import company4 from '~/images/companies/company4.png';
import company5 from '~/images/companies/company5.png';
import company6 from '~/images/companies/company6.png';
import company7 from '~/images/companies/company7.png';
import company8 from '~/images/companies/company8.png';
import company9 from '~/images/companies/company9.png';
import company10 from '~/images/companies/company10.png';
import company11 from '~/images/companies/company11.png';
import company12 from '~/images/companies/company12.png';
import company13 from '~/images/companies/company13.png';
import company14 from '~/images/companies/company14.png';
import company15 from '~/images/companies/company15.png';
import company16 from '~/images/companies/company16.png';
import company17 from '~/images/companies/company17.png';
import company18 from '~/images/companies/company18.png';
import company19 from '~/images/companies/company19.png';
import company20 from '~/images/companies/company20.png';
import Link from 'next/link';

const images = [
  company1,
  company2,
  company3,
  company4,
  company5,
  company6,
  company7,
  company8,
  company9,
  company10,
  company11,
  company12,
  company13,
  company14,
  company15,
  company16,
  company17,
  company18,
  company19,
  company20,
];

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const session = await getSession(context);
  if (session) {
    if (session.user.role === 'ADMIN') {
      return {
        redirect: {
          destination: '/admin/dashboard/',
          permanent: false,
        },
      };
    }
    return {
      redirect: {
        destination: '/dashboard',
        permanent: false,
      },
    };
  }
  return {
    props: {},
  };
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Studo Industry</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='mx-10 my-10 md:mx-20 '>
        <div>
          <div className='flex flex-col-reverse justify-center  text-center md:my-40 md:flex-col'>
            <div>
              <h1 className=' blue-orange-gradient bg-gradient-to-r bg-clip-text pb-5 text-3xl font-bold text-transparent md:text-5xl '>
                Create your Best Work Together
              </h1>
              <p className='pb-7 text-xl text-gray-500  md:text-3xl'>
                All in One solution for connecting link between student,
                industry and mentors.
              </p>
              <Link
                href='/auth/signin'
                className='Button blue-orange-gradient gradient-btn mb-6 bg-gradient-to-bl text-lg'
                // onClick={() => {
                //   void signIn();
                // }}
              >
                Sign Up for free
              </Link>
            </div>
            <div className='grid place-items-center md:grid-cols-3'>
              <Image
                src={vector1}
                width={280}
                height={130}
                alt='vector image1'
                className=''
              />
              <Image
                src={vector2}
                width={280}
                height={130}
                alt='vector image2'
                className='hidden md:block'
              />
              <Image
                src={vector3}
                width={280}
                height={130}
                alt='vector image3'
                className='hidden md:block'
              />
            </div>
          </div>
          <hr />
          <div className='my-10 md:my-28'>
            <h1 className='mb-20 text-center text-3xl font-bold md:text-5xl'>
              Perfect fit for everyone
            </h1>
            <div className='flex flex-col items-center gap-8 md:flex-row md:justify-evenly md:gap-20'>
              <LandingPageCard
                title='Student'
                description="StudoIndustry offers students real-world experience, skill development, networking, and career advancement. It bridges academia-industry gaps, prepares them for the professional world, and enhances employability. It's a holistic learning experience that boosts resumes and opens doors to long-term opportunities"
              />
              <LandingPageCard
                title='Industry'
                description="StudoIndustry bridges academia and industry, fostering innovation through collaboration with students. It offers fresh industry-relevant projects, while industries gain access to the latest trends and potential future employees. It's a win-win for driving innovation and addressing industry challenges."
              />
              <LandingPageCard
                title='Mentor'
                description="StudoIndustry empowers mentors to shape the future by sharing expertise, guiding students, and contributing to industry development. It offers a platform to stay updated, nurture talent, showcase leadership, expand networks, and find personal fulfillment in positively impacting students' lives."
              />
            </div>
          </div>
          <div className='my-20'>
            <h1 className='font-inter mb-20 text-center text-3xl font-bold md:text-5xl'>
              Trusted by well known companies
            </h1>
            <div className='animate-sliding scrollbar-thin scrollbar-track-gray-100 scrollbar-thumb-gray-400 md:scrollbar-none grid grid-cols-4 flex-row items-center justify-evenly gap-10 overflow-x-scroll md:flex md:flex-wrap'>
              {images.map((image, index) => (
                <Image
                  key={index}
                  width={100}
                  height={100}
                  src={image}
                  alt='company'
                />
              ))}
            </div>
          </div>
          <hr />
          <div className='my-20 flex flex-col items-center gap-20 text-center md:mx-20 md:gap-0 '>
            <div className='flex flex-col items-center gap-20 md:h-screen md:flex-row'>
              <Image
                width={450}
                height={300}
                src={image1}
                alt='vector image1'
              />
              <div>
                <h1 className='mb-7 text-3xl  font-bold md:text-5xl'>
                  Live Industrial Projects
                </h1>
                <p>
                  are an invaluable opportunity for students to gain hands-on
                  experience in a real-world industrial setting. These projects
                  provide students with practical exposure to industry
                  processes, technologies, and challenges. By working directly
                  with industry professionals, students can apply their
                  theoretical knowledge, develop problem-solving skills, and
                  enhance their understanding of industry practices. Live
                  industrial projects also allow students to collaborate with
                  industry experts, building professional networks and gaining
                  insights into career pathways. Additionally, these projects
                  provide a platform for students to showcase their skills and
                  potential to potential employers. live industrial projects
                  offer a dynamic learning experience that prepares students for
                  the demands and expectations of the professional world.
                </p>
                <button
                  className='Button blue-orange-gradient gradient-btn mt-7 bg-gradient-to-bl text-lg'
                  onClick={() => {
                    void signIn();
                  }}
                >
                  Apply Now
                </button>
              </div>
            </div>
            <div className='flex flex-col-reverse items-center gap-20  md:h-screen md:flex-row'>
              <div>
                <h1 className='mb-7 text-3xl  font-bold md:text-5xl'>
                  Build for teamwork
                </h1>
                <p>
                  Teamwork is a fundamental aspect of the StudoIndustry model,
                  fostering collaboration and synergy among students, mentors,
                  and industry professionals. In StudoIndustry, teams are formed
                  to work on various projects, allowing students to learn and
                  grow together. Through teamwork, students gain insights from
                  different perspectives, share knowledge, and leverage each
                  other&#39;s strengths. Collaboration in teams promotes
                  effective communication, coordination, and division of tasks,
                  leading to efficient project execution. Teamwork also nurtures
                  interpersonal skills, such as leadership, conflict resolution,
                  and cooperation, essential for professional success.
                  StudoIndustry emphasizes the value of teamwork in creating a
                  supportive and dynamic learning environment.
                </p>
                <button
                  className='Button blue-orange-gradient gradient-btn mt-7 bg-gradient-to-bl text-lg'
                  onClick={() => {
                    void signIn();
                  }}
                >
                  Apply Now
                </button>
              </div>
              <Image
                width={450}
                height={300}
                src={image1}
                alt='vector image1'
              />
            </div>
            <div className='flex flex-col items-center  gap-20 md:h-screen md:flex-row'>
              <Image
                width={450}
                height={300}
                src={image1}
                alt='vector image1'
              />
              <div>
                <h1 className='mb-7 text-3xl  font-bold md:text-5xl'>
                  Industry Certified Projects
                </h1>
                <p>
                  Students have the opportunity to work on industry-certified
                  projects. These projects are designed in collaboration with
                  industry partners, ensuring that they align with real-world
                  industry standards and requirements. By working on
                  industry-certified projects, students gain valuable experience
                  and exposure to the actual challenges and complexities of the
                  industry. The certification of these projects adds credibility
                  and recognition to the work done by students, making it a
                  valuable addition to their portfolio and resume.
                  Industry-certified projects also provide students with a
                  competitive edge in the job market, as they demonstrate their
                  ability to deliver results that meet industry expectations.
                  StudoIndustry offers students the chance to work on projects
                  that are not only academically rigorous but also relevant and
                  recognized by the industry
                </p>
                <button
                  className='Button blue-orange-gradient gradient-btn mt-7 bg-gradient-to-bl text-lg'
                  onClick={() => {
                    void signIn();
                  }}
                >
                  Apply Now
                </button>
              </div>
            </div>
          </div>
          <hr />
          <div className='my-36 text-center'>
            <h1 className='font-inter mb-2 text-center text-3xl  font-bold md:text-5xl'>
              Industrial Projects for Everyone
            </h1>
            <p>Make your projects with the guidance of industrial experts.</p>
            <Image
              width={1100}
              src={image2}
              alt='vector image1'
              className=' my-16 md:mx-auto'
            />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
